export type MapIconPlacement = {
  id: number;
  dayId: number;
  libraryIconId: number;
  trajectoryIdentifier: number;
  posXPct: number;
  posYPct: number;
  tituloContenido?: string | null;
  textoDescriptivo?: string | null;
  rutaImagenLocal?: string | null;
  rutaVideoLocal?: string | null;
  imagenDataUrl?: string | null;
  videoDataUrl?: string | null;
  imagenEstado?: "empty" | "available" | "missing" | "unreadable";
  videoEstado?: "empty" | "available" | "missing" | "unreadable";
  createdAt: string;
  updatedAt: string;
  nombreIcono?: string;
  iconoDataUrl?: string | null;
};
